// The building blocks, each checked against the Hawkeye server's own output (vectors.json is
// generated by the server's ledger and Merkle code) and each with a tampered control that must fail.
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import { derToRaw, verifyEcdsaP256, sha256hex } from '../src/crypto.mjs';
import { verifyChain, GENESIS } from '../src/chain.mjs';
import { foldProof, merkleRoot, raceLeaf, verifyAllRaces, verifyRaceProof, EMPTY_ROOT } from '../src/merkle.mjs';
import { crossCheckAnchor, parseArtifact } from '../src/artifact.mjs';

const V = JSON.parse(fs.readFileSync(new URL('./fixtures/vectors.json', import.meta.url), 'utf8'));
const clone = (x) => JSON.parse(JSON.stringify(x));

test('sha256 matches Node over non-ASCII text', async () => {
  const s = 'naira ₦ · yorùbá · ọ̀rọ̀';
  assert.equal(await sha256hex(s), crypto.createHash('sha256').update(s).digest('hex'));
});

test('ECDSA: a Node DER signature verifies; the wrong data or key does not', async () => {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' });
  const pem = publicKey.export({ type: 'spki', format: 'pem' });
  const data = 'hawkeye-ledger-anchor|v1|head=abc';
  for (let i = 0; i < 20; i += 1) { // short r or s values need left-padding; 20 rounds meets some
    const sig = crypto.sign('sha256', Buffer.from(data + i), privateKey);
    assert.equal(derToRaw(sig).length, 64);
    assert.equal(await verifyEcdsaP256({ publicKeyPem: pem, signatureDer: sig, data: data + i }), true);
  }
  const sig = crypto.sign('sha256', Buffer.from(data), privateKey);
  assert.equal(await verifyEcdsaP256({ publicKeyPem: pem, signatureDer: sig, data: `${data}x` }), false);
  const other = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' }).publicKey.export({ type: 'spki', format: 'pem' });
  assert.equal(await verifyEcdsaP256({ publicKeyPem: other, signatureDer: sig, data }), false);
});

test('chain: the server-built chain verifies to the server head', async () => {
  const r = await verifyChain(V.chain.entries);
  assert.deepEqual(r, { ok: true, entries: V.chain.entries.length, head: V.chain.head });
  assert.equal(V.genesis, GENESIS);
});

test('chain: pages continue where the last one ended', async () => {
  const first = await verifyChain(V.chain.entries.slice(0, 2));
  const rest = await verifyChain(V.chain.entries.slice(2), { prev: first.head, count: first.entries });
  assert.equal(rest.head, V.chain.head);
  assert.equal(rest.entries, V.chain.entries.length);
});

test('chain controls: an edited payload, a removed entry and a swapped order all break it', async () => {
  const edited = clone(V.chain.entries);
  edited[2].ledger_payload = edited[2].ledger_payload.replace('"c"', '"C"');
  assert.equal((await verifyChain(edited)).brokenAtId, 3);

  const removed = clone(V.chain.entries);
  removed.splice(1, 1);
  assert.equal((await verifyChain(removed)).brokenAtId, 3);

  const swapped = clone(V.chain.entries);
  [swapped[3], swapped[4]] = [swapped[4], swapped[3]];
  assert.equal((await verifyChain(swapped)).ok, false);
});

test('merkle: every tree size gives the server root, and every proof folds to it', async () => {
  assert.equal(await merkleRoot([]), V.emptyRoot);
  assert.equal(EMPTY_ROOT, V.emptyRoot);
  for (const t of V.trees) {
    assert.equal(await merkleRoot(t.leaves), t.root, `root for ${t.leaves.length} leaves`);
    for (let i = 0; i < t.leaves.length; i += 1) {
      assert.equal(await foldProof(t.leaves[i], t.proofs[i]), t.root, `proof ${i} of ${t.leaves.length}`);
    }
  }
});

test('races: every server race rebuilds, alone and all together', async () => {
  const { racesRoot, races } = V.races;
  assert.ok(races.length > 3);
  for (const r of races) {
    assert.equal(await raceLeaf(r), r.leaf);
    assert.equal((await verifyRaceProof({ ...r, racesRoot })).ok, true, r.raceKey);
  }
  const rows = races.map((r) => ({ race_key: r.raceKey, race_head: r.head, entries: r.entries, leaf_index: r.leafIndex }));
  assert.equal((await verifyAllRaces(rows, racesRoot)).ok, true);
});

test('race controls: a changed count, a changed proof step and a dropped race all fail', async () => {
  const { racesRoot, races } = V.races;
  const one = clone(races[1]);
  assert.equal((await verifyRaceProof({ ...one, entries: one.entries + 1, racesRoot })).ok, false);

  const bent = clone(races[1]);
  bent.proof[0].hash = bent.proof[0].hash.replace(/^./, (c) => (c === '0' ? '1' : '0'));
  assert.equal((await verifyRaceProof({ ...bent, racesRoot })).ok, false);

  const rows = races.slice(1).map((r, i) => ({ race_key: r.raceKey, race_head: r.head, entries: r.entries, leaf_index: i }));
  assert.equal((await verifyAllRaces(rows, racesRoot)).ok, false);
});

test('artifact: a real anchor parses, and a site figure that differs is caught', () => {
  const { anchor } = JSON.parse(fs.readFileSync(new URL('./fixtures/anchor-1395.json', import.meta.url), 'utf8'));
  const fields = parseArtifact(anchor.artifact);
  assert.equal(fields.election, '2027 Presidential Election');
  const ok = crossCheckAnchor(anchor);
  assert.equal(ok.ok, true);
  assert.ok(ok.compared.length >= 9);

  const lied = crossCheckAnchor({ ...anchor, entries: anchor.entries + 5 });
  assert.equal(lied.ok, false);
  assert.equal(lied.mismatches[0].field, 'entries');
  assert.throws(() => parseArtifact('something-else|v1|head=1'));
});
